export interface RecipeItem {
  id: string;
  name: string;
  image: string;
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  prepTime: number;
  servings: number;
  tags: string[];
  mealType: string[];
  cuisine: string;
  difficulty: string;
  ingredients: string[];
  instructions: string;
}

export const MOCK_RECIPES: RecipeItem[] = [
  {
    id: '1',
    name: 'Greek Yogurt Parfait',
    image: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&w=400',
    calories: 320,
    protein: 18,
    carbs: 42,
    fat: 8,
    prepTime: 5,
    servings: 1,
    tags: ['high-protein', 'vegetarian', 'quick'],
    mealType: ['breakfast', 'snack'],
    cuisine: 'Mediterranean',
    difficulty: 'Easy',
    ingredients: ['200g Greek yogurt', '1/2 cup granola', '1/2 cup mixed berries', '1 tbsp honey'],
    instructions: 'Layer yogurt, granola, and berries. Drizzle with honey. Serve immediately.',
  },
  {
    id: '2',
    name: 'Avocado Toast with Eggs',
    image: 'https://images.pexels.com/photos/704569/pexels-photo-704569.jpeg?auto=compress&w=400',
    calories: 420,
    protein: 22,
    carbs: 35,
    fat: 22,
    prepTime: 10,
    servings: 1,
    tags: ['vegetarian', 'high-protein'],
    mealType: ['breakfast'],
    cuisine: 'American',
    difficulty: 'Easy',
    ingredients: ['2 slices sourdough', '1 avocado', '2 eggs', 'salt', 'pepper', 'red pepper flakes'],
    instructions: 'Toast bread. Mash avocado with salt and pepper. Poach or fry eggs. Top toast with avocado and eggs.',
  },
  {
    id: '3',
    name: 'Grilled Chicken Caesar Salad',
    image: 'https://images.pexels.com/photos/2097090/pexels-photo-2097090.jpeg?auto=compress&w=400',
    calories: 480,
    protein: 45,
    carbs: 18,
    fat: 24,
    prepTime: 20,
    servings: 1,
    tags: ['high-protein', 'low-carb'],
    mealType: ['lunch', 'dinner'],
    cuisine: 'American',
    difficulty: 'Medium',
    ingredients: ['200g chicken breast', 'romaine lettuce', 'caesar dressing', 'parmesan', 'croutons', 'lemon'],
    instructions: 'Grill seasoned chicken. Toss romaine with caesar dressing. Top with sliced chicken, parmesan, and croutons.',
  },
  {
    id: '4',
    name: 'Salmon with Roasted Vegetables',
    image: 'https://images.pexels.com/photos/1860196/pexels-photo-1860196.jpeg?auto=compress&w=400',
    calories: 520,
    protein: 42,
    carbs: 28,
    fat: 26,
    prepTime: 30,
    servings: 1,
    tags: ['high-protein', 'omega-3', 'keto-friendly'],
    mealType: ['dinner'],
    cuisine: 'Mediterranean',
    difficulty: 'Medium',
    ingredients: ['180g salmon fillet', 'broccoli', 'bell peppers', 'zucchini', 'olive oil', 'garlic', 'lemon'],
    instructions: 'Preheat oven to 200°C. Toss vegetables with olive oil and garlic. Roast 20 mins. Pan-sear salmon 4 mins each side.',
  },
  {
    id: '5',
    name: 'Quinoa Buddha Bowl',
    image: 'https://images.pexels.com/photos/1640770/pexels-photo-1640770.jpeg?auto=compress&w=400',
    calories: 450,
    protein: 20,
    carbs: 58,
    fat: 16,
    prepTime: 25,
    servings: 1,
    tags: ['vegan', 'high-fiber', 'plant-based'],
    mealType: ['lunch', 'dinner'],
    cuisine: 'Mediterranean',
    difficulty: 'Easy',
    ingredients: ['1 cup quinoa', 'chickpeas', 'cucumber', 'cherry tomatoes', 'red onion', 'tahini', 'lemon'],
    instructions: 'Cook quinoa. Roast chickpeas with spices. Assemble bowl with quinoa, chickpeas, raw vegetables, and tahini dressing.',
  },
  {
    id: '6',
    name: 'Turkey & Veggie Stir-Fry',
    image: 'https://images.pexels.com/photos/262897/pexels-photo-262897.jpeg?auto=compress&w=400',
    calories: 400,
    protein: 38,
    carbs: 32,
    fat: 12,
    prepTime: 20,
    servings: 2,
    tags: ['high-protein', 'low-fat'],
    mealType: ['lunch', 'dinner'],
    cuisine: 'Asian',
    difficulty: 'Easy',
    ingredients: ['300g ground turkey', 'snap peas', 'bell peppers', 'soy sauce', 'ginger', 'garlic', 'sesame oil', 'rice'],
    instructions: 'Brown turkey in wok. Add vegetables, soy sauce, ginger, garlic. Stir-fry 5 mins. Serve over rice.',
  },
  {
    id: '7',
    name: 'Overnight Oats',
    image: 'https://images.pexels.com/photos/1099680/pexels-photo-1099680.jpeg?auto=compress&w=400',
    calories: 380,
    protein: 14,
    carbs: 60,
    fat: 10,
    prepTime: 5,
    servings: 1,
    tags: ['vegan', 'meal-prep', 'high-fiber'],
    mealType: ['breakfast'],
    cuisine: 'American',
    difficulty: 'Easy',
    ingredients: ['1/2 cup rolled oats', '1 cup almond milk', 'chia seeds', 'banana', 'peanut butter', 'honey'],
    instructions: 'Combine oats, milk, and chia seeds. Refrigerate overnight. Top with banana, peanut butter, and honey.',
  },
  {
    id: '8',
    name: 'Black Bean Tacos',
    image: 'https://images.pexels.com/photos/461198/pexels-photo-461198.jpeg?auto=compress&w=400',
    calories: 420,
    protein: 18,
    carbs: 62,
    fat: 12,
    prepTime: 15,
    servings: 2,
    tags: ['vegan', 'high-fiber', 'mexican'],
    mealType: ['lunch', 'dinner'],
    cuisine: 'Mexican',
    difficulty: 'Easy',
    ingredients: ['1 can black beans', 'corn tortillas', 'avocado', 'salsa', 'lime', 'cilantro', 'red cabbage'],
    instructions: 'Warm beans with cumin and garlic. Heat tortillas. Fill with beans, top with avocado, salsa, cabbage, and lime.',
  },
  {
    id: '9',
    name: 'Protein Smoothie Bowl',
    image: 'https://images.pexels.com/photos/1099683/pexels-photo-1099683.jpeg?auto=compress&w=400',
    calories: 340,
    protein: 25,
    carbs: 44,
    fat: 8,
    prepTime: 5,
    servings: 1,
    tags: ['high-protein', 'vegetarian', 'quick'],
    mealType: ['breakfast', 'snack'],
    cuisine: 'American',
    difficulty: 'Easy',
    ingredients: ['1 scoop protein powder', 'frozen banana', 'frozen berries', 'almond milk', 'granola', 'fresh fruit'],
    instructions: 'Blend protein powder with frozen fruit and minimal milk until thick. Pour into bowl and top with granola and fresh fruit.',
  },
  {
    id: '10',
    name: 'Lentil Soup',
    image: 'https://images.pexels.com/photos/539451/pexels-photo-539451.jpeg?auto=compress&w=400',
    calories: 360,
    protein: 22,
    carbs: 54,
    fat: 6,
    prepTime: 35,
    servings: 4,
    tags: ['vegan', 'high-fiber', 'high-protein'],
    mealType: ['lunch', 'dinner'],
    cuisine: 'Mediterranean',
    difficulty: 'Easy',
    ingredients: ['2 cups red lentils', 'onion', 'carrots', 'celery', 'cumin', 'turmeric', 'tomatoes', 'vegetable broth'],
    instructions: 'Sauté vegetables. Add lentils, broth, and spices. Simmer 25 minutes until lentils are soft. Season and serve.',
  },
  {
    id: '11',
    name: 'Baked Chicken Breast',
    image: 'https://images.pexels.com/photos/2673353/pexels-photo-2673353.jpeg?auto=compress&w=400',
    calories: 280,
    protein: 52,
    carbs: 4,
    fat: 6,
    prepTime: 30,
    servings: 2,
    tags: ['high-protein', 'low-carb', 'keto-friendly'],
    mealType: ['lunch', 'dinner'],
    cuisine: 'American',
    difficulty: 'Easy',
    ingredients: ['2 chicken breasts', 'olive oil', 'garlic powder', 'paprika', 'oregano', 'salt', 'pepper'],
    instructions: 'Coat chicken with oil and spices. Bake at 200°C for 20-25 minutes until internal temperature reaches 74°C.',
  },
  {
    id: '12',
    name: 'Shrimp Pad Thai',
    image: 'https://images.pexels.com/photos/699953/pexels-photo-699953.jpeg?auto=compress&w=400',
    calories: 520,
    protein: 32,
    carbs: 68,
    fat: 14,
    prepTime: 25,
    servings: 2,
    tags: ['high-protein', 'asian'],
    mealType: ['lunch', 'dinner'],
    cuisine: 'Asian',
    difficulty: 'Medium',
    ingredients: ['200g shrimp', 'rice noodles', 'eggs', 'bean sprouts', 'green onions', 'peanuts', 'pad thai sauce', 'lime'],
    instructions: 'Soak noodles. Stir-fry shrimp, push aside and scramble eggs. Add noodles, sauce, bean sprouts. Top with peanuts and lime.',
  },
];

export const MEAL_CATEGORIES = ['breakfast', 'lunch', 'dinner', 'snack'] as const;
export const CUISINES = ['American', 'Italian', 'Asian', 'Mexican', 'Mediterranean', 'Indian', 'French', 'Japanese'];
export const DIET_TAGS = ['vegan', 'vegetarian', 'keto-friendly', 'high-protein', 'low-carb', 'gluten-free', 'high-fiber', 'low-fat'];
